# Generated by Django 3.2.20 on 2023-07-25 15:58

from django.db import migrations, models


def assign_attributes_to_pages(apps, schema_editor):
    AttributePage = apps.get_model("attribute", "AttributeProduct")

    for attribute_page in AttributePage.objects.all():
        for page in attribute_page.assigned_pages.all():
            attribute = attribute_page.attribute

            # Check if this attribute hasn't already been added
            if page.new_attributes.filter(attributes=attribute).exists():
                continue

            page.new_attributes.add(attribute)
            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0030_auto_20230725_1558"),
        ("page", "0028_add_default_page_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="new_attributes",
            field=models.ManyToManyField(
                blank=True, related_name="new_pages", to="attribute.Attribute"
            ),
        ),
        migrations.RunPython(assign_attributes_to_pages),
    ]
