# Generated by Django 3.2.20 on 2023-07-11 16:10

from django.db import migrations, models
import django.db.models.deletion
from django.db.models.signals import post_migrate
from django.apps import apps as registry

from .tasks.saleor3_16 import assign_products_to_attribute_values_task


def enqueue_data_migration(apps, _schema_editor):
    def on_migrations_complete(sender=None, **kwargs):
        assign_products_to_attribute_values_task.delay()

    sender = registry.get_app_config("attribute")
    post_migrate.connect(on_migrations_complete, weak=False, sender=sender)


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0029_alter_attribute_unit"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="attributeproduct",
            name="assigned_products",
        ),
        migrations.RemoveField(
            model_name="assignedproductattributevalue",
            name="assignment",
        ),
        migrations.DeleteModel(
            name="AssignedProductAttribute",
        ),
        migrations.AlterUniqueTogether(
            name="assignedproductattributevalue",
            unique_together={("value", "product")},
        ),
    ]

    operations = [
        # Set FKs to allow null values before marking their models/fields deleted
        migrations.AlterField(
            model_name="assignedproductattributevalue",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productvalueassignment",
                to="attribute.AssignedProductAttribute",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignedproductattribute",
            unique_together={},
        ),
        migrations.AlterField(
            model_name="assignedproductattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributes",
                to="product.Product",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignedproductattribute",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productassignments",
                to="attribute.AttributeProduct",
                null=True,
            ),
        ),
        # Remove FK constraints so that the DB doesn't try to truncate the references
        migrations.RunSQL(
            """
            ALTER TABLE attribute_assignedproductattribute
            DROP CONSTRAINT IF EXISTS
            attribute_assignedpr_assignment_id_f65ddd91_fk_attribute;


            ALTER TABLE attribute_assignedproductattribute
            DROP CONSTRAINT IF EXISTS
            attribute_assignedpr_product_id_c267932a_fk_product_p;


            ALTER TABLE attribute_assignedproductattributevalue
            DROP CONSTRAINT IF EXISTS
            attribute_assignedpa_assignment_id_6863be0a_fk_attribute
            """
        ),
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        # Add a new field
        migrations.AddField(
            model_name="assignedproductattributevalue",
            name="product",
            field=models.ForeignKey(
                null=True,
                blank=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributevalues",
                to="product.Product",
            ),
        ),
        migrations.RunPython(enqueue_data_migration, migrations.RunPython.noop),
    ]
