# Generated by Django 3.2.20 on 2023-07-25 15:58

from django.db import migrations, models
import django.db.models.deletion


def assign_pages_to_attribute_values(apps, schema_editor):
    AssignedPageAttributeValue = apps.get_model(
        "attribute", "AssignedPageAttributeValue"
    )

    for attribute_value in AssignedPageAttributeValue.objects.all():
        attribute_value.new_page = attribute_value.assignment.page
        attribute_value.save()


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0028_add_default_page_type"),
        ("attribute", "0029_alter_attribute_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedpageattributevalue",
            name="new_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributevalues",
                to="page.page",
            ),
        ),
        migrations.RunPython(assign_pages_to_attribute_values),
        migrations.RemoveField(
            model_name="attributepage",
            name="assigned_pages",
        ),
        migrations.AlterUniqueTogether(
            name="assignedpageattributevalue",
            unique_together={("value", "new_page")},
        ),
        migrations.RemoveField(
            model_name="assignedpageattributevalue",
            name="assignment",
        ),
        migrations.DeleteModel(
            name="AssignedPageAttribute",
        ),
    ]
