# Generated by Django 3.2.20 on 2023-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0030_simplify_product_attribute_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributevalue",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="value",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="attributevaluetranslation",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
