# Generated by Django 3.2.17 on 2023-02-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0072_merge_20230207_1030"),
        ("account", "0075_add_address_metadata"),
    ]

    operations = []
